products = [
    {
      '_id': '1',
      'name': 'Airpods Wireless Bluetooth Headphones',
      'image': '/images/airpods.jpg',
      'description':
        'A tecnologia Bluetooth permite conectá-lo com dispositivos compatíveis sem fio O áudio AAC de alta qualidade oferece experiência de escuta imersiva O microfone embutido permite que você atee chamadas enquanto trabalha',
      'brand': 'Apple',
      'category': 'Eletrônicos',
      'price': 89.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'iPhone 11 Pro 256GB Memory',
      'image': '/images/phone.jpg',
      'description':
        'Apresentando o iPhone 11 Pro. Um sistema transformador de câmera tripla que adiciona toneladas de capacidade sem complexidade. Um salto sem precedentes na vida útil da bateria',
      'brand': 'Apple',
      'category': 'Eletrônicos',
      'price': 599.99,
      'countInStock': 7,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Cannon EOS 80D DSLR Camera',
      'image': '/images/camera.jpg',
      'description':
        'Caracterizado por especificações versáteis de imagem, a Canon EOS 80D esclarece ainda mais usando um par de sistemas de foco robustos e um design intuitivo',
      'brand': 'Cannon',
      'category': 'Eletrônicos',
      'price': 929.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Sony Playstation 4 Pro White Version',
      'image': '/images/playstation.jpg',
      'description':
        'O melhor centro de entretenimento doméstico começa com o PlayStation. Se você gosta de jogos, filmes em HD, televisão, música',
      'brand': 'Sony',
      'category': 'Eletrônicos',
      'price': 399.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Logitech G-Series Gaming Mouse',
      'image': '/images/mouse.jpg',
      'description':
        'Tenha uma melhor controle sobre seus jogos com este mouse de jogos Logitech LIGHTSYNC. Os seis botões programáveis permitem personalização para uma experiência de jogo suave',
      'brand': 'Logitech',
      'category': 'Eletrônicos',
      'price': 49.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Amazon Echo Dot 3rd Generation',
      'image': '/images/alexa.jpg',
      'description':
        'Conheça o Echo Dot - Nosso alto-falante inteligente mais popular com design de tecido. É o nosso alto-falante inteligente mais compacto que se encaixa perfeitamente em um espaço pequeno',
      'brand': 'Amazon',
      'category': 'Eletrônicos',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
]
